### PR TITLE
Throw a dedicated exception if the managed container process dies

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jamezp could you please review and eventually merge? 

The motivation for this change is quite simple: If the process that starts the managed server dies for whatever reason, it should not be reported as a timeout (as we do now).

**Comment by ppalaga** [comment]
For the record: I came a across this when my PR was not passing on @jpkrohling 's Jenkins that happened to have too little RAM. The message saying "Managed server was not started within [420] s" came only  ~30 seconds after starting the container, which apparently made no sense. With a little bit debugging, I found out that it is not a timeout, but that rather the container process exited with code 137 which usually means that it was killed by the OS. After looking into `journalctl`, indeed, I saw 

```
Apr 01 19:56:29 caipora kernel: Out of memory: Kill process 31617 (java) score 355 or sacrifice child
Apr 01 19:56:29 caipora kernel: Killed process 31617 (java) total-vm:3591480kB, anon-rss:582232kB, file-rss:0kB
```

That said, it would save me a little bit time to see a error correct message from the managed container.

**Comment by jamezp** [comment]
I think this makes sense. The only thing I wonder is if we should throw a `LifecycleException` instead of a `RuntimeException` and add a catch that would just rethrow any `LifecycleException` instead of wrapping it.

What do you think @ppalaga?

**Comment by ppalaga** [comment]
@jamezp 3a06ad1 adopts your proposal.

**Comment by jamezp** [comment]
Excellent, thanks! I think this look good.

**Pull request merged**
