### PR TITLE
WFLY-4255 [1.0.x]

### PR DESCRIPTION
**Pull request by rhusar**
Allow Arquillian to specify a timeout value for the WildFly clean shutdown mechanism when shutting down a server

Upstream master
https://github.com/wildfly/wildfly-arquillian/pull/13

### CODE REVIEW

**Comment by rachmatowicz** [comment]
@jamezp @rhusar Can we get this request merged asap and a new version of wildfly-arquillian tagged? This feature is required for testing clean shutdown in WFLY-4255.

**Comment by jfclere** [comment]
Please review and merge.

**Comment by jamezp** [comment]
I'm not in favor of having this in a 1.0.x version. I think we can put it upstream (1.1.x) though.

**Comment by jamezp** [comment]
Closing this as I don't think it belongs in 1.0 branch. I'll be merging the #13 into master after one more review.

**Pull request closed without merging**
