### PR TITLE
Update arquillian-core to 1.1.10.Final & shrinkwrap-descriptors to 2.0.0-alpha-8

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by ctomc** [comment]
duplicate of https://github.com/wildfly/wildfly-arquillian/pull/47

**Comment by MatousJobanek** [comment]
Sorry, haven't noticed... Will you update also the version of shrinkwrap-descriptors to 2.0.0-alpha-8? Or shall I create separate PR?

**Comment by ctomc** [comment]
it updates shrinkwrap as well.

**Comment by MatousJobanek** [comment]
OK, I have read only the title of your PR, so I suggested that it updates only the arquillian-core. My apologies.
Closing this PR...

**Pull request closed without merging**
