### PR TITLE
[WFLY-4537] Servlet protocol leaks into all containers

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by ctomc** [comment]
makes sense

**Comment by tdiesler** [comment]
Is this waiting on something? I'd like to see this in 9.0.0.CR1

**Comment by ctomc** [comment]
@jamezp any chance we can do merge & beta1 release of wildfly-arquillian?
@tdiesler wdym by getting it into 9.0.0.CR1? that boat already sailed. CR1 was released on Friday. 

As for wildfly arquillian adapters / containers goes they are not part of distribution anyhow. So no need to have them in CR1/Final as this is whole idea of separate repo and separate versioning. WildFly only uses it for running parts of the testsuite.

**Comment by stuartwdouglas** [comment]
I am not going to merge this, having the servlet protocol be included by default is a deliberate decision designed to make life easier for our end users (they just need to include the container, not the container and the protocol). For our internal testing where we want to use the JMX protocol it is a simple matter to exclude servlet, or manually set the protocol in arquillian.xml. 

Basically this would be an API change (as existing pom's would stop working on upgrade), and it will break the 99% case to make the 1% case slightly easier.

**Pull request closed without merging**
